# -*- coding: utf-8 -*-
u'''Generated by unittest-skeleton-generator.sh on 2022-07-19 at 15:42:24.
'''
import os
import sys
import unittest
import mock

maya_modules = [
    'maya',
    'maya.app',
    'maya.app.general',
    'maya.app.general.mayaMixin',
    'cmds',
    'mel',
    'pymel',
    'pymel.core'
    'MayaQWidgetBaseMixin',
    'MayaQWidgetDockableMixin',
    'PySide2',
    'PySide2.QtUiTools',
    'QtWidgets',
    'QUiLoader'
]

# Creates the mocks.
for mod in maya_modules:
    sys.modules[mod] = mock.MagicMock()

# Automatically calculated by unittest-skeleton-generator.sh to easily import functions.py:
# Gets the src_dir.
tests_dir = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
root_dir = os.path.dirname(tests_dir)
src_dir = os.path.join(root_dir, "src")

# Adds src_dir to sys.path if it is not already there:
for path in sys.path:
    if path == src_dir:
        break
else:
    sys.path.append(src_dir)


import shared.functions


class FunctionsTestCase(unittest.TestCase):

    def setUp(self):
        pass

    def tearDown(self):
        pass

    # # Covers add_site_packages_to_sys_path.
    # def test_add_site_packages_to_sys_path(self):
    #     pass

    # # Covers constant.
    # def test_constant(self):
    #     pass

    # # Covers fset.
    # def test_fset(self):
    #     pass

    # # Covers fget.
    # def test_fget(self):
    #     pass

    # # Covers get_subdir_full_paths.
    # def test_get_subdir_full_paths(self):
        pass

    # Covers number_format.
    def test_number_format(self):
        expected = "17.00"
        result = shared.functions.number_format(17, 2)
        self.assertEqual(expected, result)

    # # Covers password_hash.
    # def test_password_hash(self):
    #     pass

    # # Covers password_verify.
    # def test_password_verify(self):
    #     pass

    # # Covers print_error_message.
    # def test_print_error_message(self):
    #     pass

    # # Covers print_sys_path.
    # def test_print_sys_path(self):
    #     pass


