# -*- coding: utf-8 -*-
u'''Generated by bashdb on 2022-07-19 at 15:38:51.
'''
import os
import sys
import unittest
import mock

maya_modules = [
    'maya',
    'maya.app',
    'maya.app.general',
    'maya.app.general.mayaMixin',
    'cmds',
    'mel',
    'pymel',
    'pymel.core'
    'MayaQWidgetBaseMixin',
    'MayaQWidgetDockableMixin',
    'PySide2',
    'PySide2.QtUiTools',
    'QtWidgets',
    'QUiLoader'
]

# Creates the mocks.
for mod in maya_modules:
    sys.modules[mod] = mock.MagicMock()

# Automatically calculated by bashdb to easily import functions.py:
# Gets the src_dir.
tests_dir = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
root_dir = os.path.dirname(tests_dir)
src_dir = os.path.join(root_dir, "src")

# Adds src_dir to sys.path if it is not already there:
for path in sys.path:
    if path == src_dir:
        break
else:
    sys.path.append(src_dir)


import shared.functions


class FunctionsTestCase(unittest.TestCase):

    def setUp(self):
        pass

    def tearDown(self):
        pass


